module.exports = {
  images: {
    domains: [
      "cache1.pbwstatic.com",
      "cache2.pbwstatic.com",
      "cache3.pbwstatic.com",
      "cache4.pbwstatic.com",
      "cache5.pbwstatic.com",
      "cache6.pbwstatic.com",
      "cache7.pbwstatic.com",
      "cache8.pbwstatic.com",
      "cache9.pbwstatic.com",
      "cache10.pbwstatic.com",
      "cache11.pbwstatic.com",
      "cache12.pbwstatic.com",
      "cache13.pbwstatic.com",
      "cache14.pbwstatic.com",
      "cache15.pbwstatic.com",
      "cache16.pbwstatic.com",
      "cache17.pbwstatic.com",
      "cache18.pbwstatic.com",
      "cache19.pbwstatic.com",
      "cache20.pbwstatic.com",
      "cache21.pbwstatic.com",
      "cache22.pbwstatic.com",
      "cache23.pbwstatic.com",
      "cache24.pbwstatic.com",
      "cache25.pbwstatic.com",
      "cache26.pbwstatic.com",
      "cache27.pbwstatic.com",
      "cache28.pbwstatic.com",
      "cache29.pbwstatic.com",
    ],
  },
};
